// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<boolean>;

export function SaveFileDialog():Promise<string>;

export function Title():Promise<string>;
