// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Header() {
  return window['go']['services']['EPW']['Header']();
}

export function Parse(arg1) {
  return window['go']['services']['EPW']['Parse'](arg1);
}
