// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileContents():Promise<string>;

export function ReadFileContents(arg1:string):Promise<string>;
