// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileContents() {
  return window['go']['services']['FileSystemService']['OpenFileContents']();
}

export function ReadFileContents(arg1) {
  return window['go']['services']['FileSystemService']['ReadFileContents'](arg1);
}
